### ISSUE TITLE
Sphere approximations are offset in some cases

### ISSUE THREAD

**Issue by vhartman** [CoMMALab/foam#2]
Hey,

Nice work. I was just searching around for some tool to approximate a mesh with primitives and found the corresponding paper - perfect timing!

There seems to be some small problem with offsets somewhere: I tried running this on the ur10e-URDF from [here](https://github.com/Daniella1/urdf_files_dataset/blob/main/urdf_files/ros-industrial/xacro_generated/universal_robots/ur_description/urdf/ur10.urdf).

In the following, I am loading the robot twice, compared to only one in the urdf above. The version with meshes looks like this:
![Image](https://github.com/user-attachments/assets/9f1c29cd-f3a7-4634-99bd-86d14b65c40e)

And the resulting sphere approximation looks like this:
![Image](https://github.com/user-attachments/assets/714fa0ac-ef4b-437b-9d83-3a272dd7ea13)

Converting meshes separately seems to be fine, i.e. the offset is not there.

I also have some version where I did approximate the meshes manually with some cylinders (i.e. same urdf as above, but the collision meshes are replaced with cylinders) [here](https://github.com/vhartman/multirobot-pathplanning-benchmark/blob/326d45d7bbf12c77635a2fc25aad41fd123eaf4a/src/multi_robot_multi_goal_planning/problems/urdfs/ur10e/ur10e_primitives.urdf), where the approximation works (unfortunately, this file has some absolute paths, since I could not yet convince pinocchio to load relative paths as I want it to).

I did not yet have time to look into this myself, but will have a look at some point if you do not have time/it is not a priority.

Thanks again for the great tool!

**Comment by zkingston** [comment]
Thanks for the kind words and the report! I think I've fixed the issue with #3 if you can take a look and see if that works for you.

**Comment by vhartman** [comment]
I am unfortunately still getting the same problem as before. Since the spherized model looks the same as before, I suspect that this could also be a problem from my side though? I re-ran  the installation commands after pulling as well (even tough that should not be necessary as far as I can tell).

The sphere approximation from ./generate_spheres.py still seems fine, so I am still a bit puzzled of where the error on my site might come from.

I also see that in the PR, you tested on the UR10, so it clearly seems to work for you?

**Comment by zkingston** [comment]
Can you remove the `sphere_database.json` file if you didn't previously? It caches results to speed up subsequent spherizations but might be still holding the previous bad values.

**Comment by vhartman** [comment]
That did in fact fix it. Thanks!
